### ISSUE TITLE
Issue with directly accessing the locally stored item

### ISSUE THREAD

**Issue by yusijs** [SirDarquan/h5webstorage#10]
Hey, I have a very weird issue. I decided to try using your service, but I'm not having a great time with it. Basically I'm trying to access localStorage["id_token"], but it's not letting me. If you look at the console output below, the first line id_token is not set, so it should indeed be undefined. Second line, it is set (see the all-object output), but directly accessing it still gives undefined. Thirdly I've deleted the item again (using your api), and it's both undefined and gone from the all-object. 

Any idea what I'm messing up? Or am I completely misusing the library?

Code:

```
 constructor(private _router: Router, private _jwtHelper: JwtHelper, private localStorage: LocalStorage) {
    let all = this.localStorage
    let token = all.getItem("id_token")
    let int = setInterval(_ => {
      console.log(token, all);
    },1000)
    setTimeout(_ => {
      clearInterval(int);
    },10000)
  }
```

Console output:

> navbar.component.ts:27 undefined LocalStorage {options: Object, storage: Storage, prevValue: "{}", fromStorage: false, subscription: Subscriber}
> 
> navbar.component.ts:27 undefined LocalStorage {id_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZ…gxNX0.vv_oXeUSKB5dR9xNRcPBOQfN9xpgCReNWxv-5c-b-vM", options: Object, storage: Storage, prevValue: "{"id_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.…NX0.vv_oXeUSKB5dR9xNRcPBOQfN9xpgCReNWxv-5c-b-vM"}", fromStorage: false…}
> navbar.component.ts:27 
> 
> navbar.component.ts:27 undefined LocalStorage {options: Object, storage: Storage, prevValue: "{}", fromStorage: false, subscription: Subscriber}

**Comment by SirDarquan** [comment]
Have you tried to assign token straight from this.localStorage instead of assigning it to all then getting id_token? I'm curious if it works.  

Also you can access "id_token" easier if you use the `@StorageProperty() string id_token;` Then you never have to use this.localStorage.getItem("id_token");

**Comment by yusijs** [comment]
I tried acvessing it directly yes and no go. I'll try via @Storageaproperty!

**Comment by SirDarquan** [comment]
Is it possible for you to setup a plunker or a branch I can clone to view the code in the way you've set things up? I may be able to diagnose it faster if you have that

**Comment by yusijs** [comment]
Sorry, worked around my problem. I'll see if I have time to set up a plunk this evening!
