### ISSUE TITLE
Include sourcemaps in npm package

### ISSUE THREAD

**Issue by delasteve** [SirDarquan/h5webstorage#6]
I am receiving the following:

```
Failed to parse SourceMap: http://localhost:4200/vendor/h5webstorage/storageproperty.js.map
```

The npm package currently does not ship with `*.js.map` files, which lead the to this error.

**Comment by SirDarquan** [comment]
Well @delasteve, I agree this is a problem but I'm going to choose a different fix. I purposely left the source .ts file out of the npm package because I feel that if I'm doing my job right, no one needs them. I accidentally left the soureMap option on during compile which is causing this problem but just to be sure, this doesn't cause your program to fail, right? It should just be an unwelcome entry in the console area while serving the files.

**Comment by delasteve** [comment]
I don't expect the `.ts` files in the npm module, and I'm sorry if it came off that way. There isn't a failure, just console errors as you mentioned. Sourcemaps aren't always necessary, but are nice to have. Other modules like jquery and even angular2 shouldn't need sourcemaps, but they provide them.

I'm okay with either solution, in or out. I was just bringing it to your attention.

**Comment by SirDarquan** [comment]
Thanks, I appreciate it. I'll try to have that fixed in a few hours.

**Comment by delasteve** [comment]
Does this mean a new version is coming? :smile:

**Comment by SirDarquan** [comment]
Coming? I released it yesterday. I just forgot to close the issue.

**Comment by delasteve** [comment]
Oh, hah. Repo hasn't been updated :-P Cool! Thanks!

**Comment by psafont** [comment]
Source maps seem to be missing again in the npm package (0.6.0)

```
$ tree node_modules/h5webstorage/
node_modules/h5webstorage/
├── basestorage.d.ts
├── basestorage.js
├── index.d.ts
├── index.js
├── localstorage.d.ts
├── localstorage.js
├── package.json
├── README.md
├── sessionstorage.d.ts
├── sessionstorage.js
├── storageproperty.d.ts
└── storageproperty.js
```

**Comment by SirDarquan** [comment]
I'm sorry about that. I really need an automated deployment process so this can be consistent. I'll try to get an update out later today. Thanks.

**Comment by psafont** [comment]
No worries! Thanks for your work :)
