### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by jkufrin** [SirDarquan/h5webstorage#7]
nodejs - ^6.2.0
npm - ^3.10.2
typings - ^1.3.1

Just downloaded the latest version of h5webstorage. It's throwing errors from index.d.ts: Cannot find module for each of the 4 support files, basestorage, localstorage etc... 

Is there something I need to install for typings to get the definition file to recognize the support?

**Comment by SirDarquan** [comment]
Thanks. I'll see if I can figure out what's going on but in general it supposed to just work.

**Comment by SirDarquan** [comment]
Well that was quick! Apparently, the definition files didn't get included in the package. I really need to get an auto-deployment process going. Anyway, I've published a newer npm package.
