### ISSUE TITLE
Localstorage and sessionstorage are too late with setting variables

### ISSUE THREAD

**Issue by stijn26** [SirDarquan/h5webstorage#8]
I have this code:

```
        localStorage['userToken'] = null;
        sessionStorage['active'] = null;
        localStorage['userTokenDate'] = null;
        userService.setToken('testToken');
        expect(localStorage['userToken']).toEqual('testToken');
        expect(sessionStorage['active']).toBeTruthy();
        expect(localStorage['userTokenDate']).toBeTruthy();
```

And the tested function:

```
setToken(token: string) {
    this.localStorage['userToken'] = token;
    this.sessionStorage['active'] = true;
    this.localStorage['userTokenDate'] = Date.now();
  }
```

The variables are still null instead of the desired values.
In the next unit test, they are the right values.

**Comment by SirDarquan** [comment]
This actually has more to do with the way Angular 2 works with change detection. Normally when some browser event occurs, the framework will execute what's called a Zone and this is what does the change detection. In testing, the Zone doesn't run the same way it does with actual code making it more difficult to test with. 

Fortunately, it's not actually the storage objects you want to test but the behavior of your function. You should be sending in mocks of the storage objects that are just simple hash objects and you'll be able to test exactly the way you described.

**Comment by stijn26** [comment]
Do you have a example of how I need to mock the localstorage with say a variable called 'mockVariable'?

I haven't succeeded yet in creating a mock service for the localstorage.

I have this now:

```
class mockLocalstorage {
    let mockVariable;
}
...
{ provide: LocalStorage, useClass: MockLocalStorage }
...
```

**Comment by SirDarquan** [comment]
Well, the Angular team changed the testing system recently so I have to figure out the exact way it works. But I'l try to give you a good idea of how it should work.

``` typescript
//MyClass.ts
@Injectable()
export MyClass{
  constructor(private localStorage: LocalStorage){}

  doSomething(){
    this.localStorage['myVariable'] = 'something awesome';
  }
}

//MyClass.tests.ts
describe("MyClass", ()=>{
  it("should set myVariable", ()=>{
    var mockLocalStorage = {};
    var sut = new MyClass(mockLocalStorage);

    sut.doSomething();
    expect(mockLocalStorage.myVariable).toBe('something awesome');
  }); 
});
```

I apologize for typos and whatnot but I came up with this example off the top of my head and wrote it in the GitHub comments text area. In your code above, you didn't show how your userService was instantiated for testing so I made an educated guess based on its name the purpose and definition and used that to create my example. Services are relatively easy to test in this manner but components  requires a different strategy but injects the mockService in about the same way. I hope this helps.

**Comment by stijn26** [comment]
Thanks for the help!

Actually this is the code for the current version of Angular:

```
let mockLocalStorage = {'myVariable': 'test'};
let mockSessionStorage = {'active': false};
...
describe('Service: UserService', () => {

  beforeEach(() => addProviders([
    UserService,
    ...
    { provide: LocalStorage, useValue: mockLocalStorage },
    { provide: SessionStorage, useValue: mockSessionStorage }
  ]));

   it('getValidLoginCheck should set the validToken variable to true when there is an active session.',
    inject(
      [UserService, SessionStorage, LocalStorage],
      (userService, sessionStorage, localstorage) => {
        sessionStorage['active'] = true;
        userService.getValidLoginCheck();
        expect(userService.validToken).toBeTruthy();
      }
    )
  );
});
```

Hopefully this code helps someone.

Thanks for the great work @SirDarquan
